### ISSUE TITLE
hello，关于文件运行问题，想请教一下

### ISSUE THREAD

**Issue by Roiko97** [sdfdzx/VRShow#1]
您好，请问一下，目前我运行您的项目，使用的是Android Studio gradle:2.2.0 。
提示报错：
Error:(30, 0) Could not find method compile() for arguments [com.github.sdfdzx:VRShow:v1.0.2 ] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

无法运行，想请问一下您应该如何处理

**Comment by DrownCoder** [comment]
你好，将你的gradle升级到3.0以上试一下
