### ISSUE TITLE
gif图大小为：17.0M，在GIF显示3D的时候手势操作不起作用，还会闪烁，请问怎么解决？

### ISSUE THREAD

**Issue by yecaler** [sdfdzx/VRShow#2]
gif图大小为：17.0M，在GIF显示3D的时候手势操作不起作用，还会闪烁，请问怎么解决？

**Comment by DrownCoder** [comment]
@supperyan 你好，方便提供一下具体GIF资源吗？闪烁可能是触发频率过快导致的，建议设置一下响应速度模式：LOW,NORMAL,FAST再试试

**Comment by yecaler** [comment]
稍等，马山发

**Comment by yecaler** [comment]
![image](https://user-images.githubusercontent.com/25024969/50721785-187c9200-1100-11e9-9ac9-51c70a9527c9.png)

**Comment by yecaler** [comment]
发不了，方便留一下邮箱吗？

**Comment by yecaler** [comment]
> @supperyan 你好，方便提供一下具体GIF资源吗？闪烁可能是触发频率过快导致的，建议设置一下响应速度模式：LOW,NORMAL,FAST再试试

发不了，方便留一下邮箱吗？

**Comment by yecaler** [comment]
我都设置过响应速度了，还是会卡顿加闪烁。

**Comment by DrownCoder** [comment]
@supperyan drowncoder@163.com

**Comment by yecaler** [comment]
@DrownCoder 已发送，感谢！

**Comment by DrownCoder** [comment]
@supperyan  你好，你这个GIF不是3D旋转的GIF图，拖拽的本质原理是改变GIF的进度，具体可以看一下[原理博客](https://www.jianshu.com/p/abd1772cb061)，关于闪烁的原因可能有两个：1.GIF本身过大，建议压缩2.手机本身性能的问题，因为我刚试的是没有闪烁的
